### ISSUE TITLE
Symbol lookup errors

### ISSUE THREAD

**Issue by rapgenic** [conda-forge/xeus_octave-feedstock#24] opened 2023-03-20 08:29 UTC
After the `osxarm64` rebuild of the package (even though I think it is not related), some strange errors started appearing at kernel run (which failed) after installing through conda-forge. I rebuilt the forge package and these seemed to disappear in local environments but a user still reports them in binder.

The error I saw (before rebuilding the package) was the following:

```
[home]/.conda/envs/test/bin/xoctave: symbol lookup error: [home]/.conda/envs/test/bin/../lib/libxeus-octave.so.0: undefined symbol: _ZN4xeus12xinterpreter21internal_request_implERKN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS1_14adl_serializerES4_IhSaIhEEEE
```

The error the user reports is the following (see jupyter-xeus/xeus-octave#104):

```
/srv/conda/envs/notebook/bin/xoctave: symbol lookup error: /srv/conda/envs/notebook/bin/../lib/libxeus-zmq.so.1: undefined symbol: _ZN4xeus12xpub_messageC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN8nlohmann10basic_jsonISt3mapSt6vectorS6_blmdSaNS9_14adl_serializerESC_IhSaIhEEEESG_SG_SG_SC_ISC_IcS5_ESaISH_EE
```

Which are very similar, and suggest they could be related to the `nlohmann_json` library. Looking online it seems that these kind of errors might be related to mismatch in library versions in the filesystem, which lead me to believe that there is some error inside the recipe file `dependencies` section.

I'm trying to understand what's the catch here, but I'm running out of ideas. 

@AntoinePrv or @SylvainCorlay maybe you have a clearer picture than me? Any suggestion would be much appreciated..

**Comment by AntoinePrv** [comment] 2023-03-20 10:11
@rapgenic Is this problem happening only on `osxarm64`? Do you have a way to reproduce it (simply launching xeus-octave?)? I seem to have no problems in a fresh environment in `linux64`.

> Looking online it seems that these kind of errors might be related to mismatch in library versions

That's likely, perhaps a version range/pin of the dependencies is too lose.

**Comment by rapgenic** [comment] 2023-03-20 10:16
Strangely enough `osxarm64` is completely out of the picture. (Other than the fact that this has happened after adding that build platform), as no one reported errors (yet).

As of now `linux64` which didn't work with build 0 of version 0.1.0, seems to be working. 

The only problematic platform ATM is the user's binder, and I'm waiting for them to send the output of `conda list` to see if the package versions are different from what we have...

**Comment by rapgenic** [comment] 2023-03-20 10:38
Ok so I found the user's repository with binder, https://github.com/skotssd/geochemicalscripts

Comparing the package list I can see that they have the following different versions (I selected only the relevant packages)

| Package|Version (me)|Build|Version (user's binder)|Build|
|-----|-----|-----|-----|-----|
| xeus-zmq | 1.0.2 | h0541b36_<b>2</b> | 1.0.2 | h0541b36_<b>0</b> |
| mesalib | 23.0.0 | **h3855f93_1** |23.0.0      |         **h0fe20ba_0** |

The `xeus-zmq` package is clearly different (even though I don't know how come I don't have the latest build), and the error reported seems to be actually caused by `xeus-zmq`

Interestingly I haven't found `nlohmann_json`. Maybe it is used on builds only? Is it possible that different builds use different versions of `nlohmann_json` which have conflicting symbols?

**Comment by rapgenic** [comment] 2023-03-20 10:45
Success!

Actually forcing conda to update the binder environment from the terminal had the kernel starting!

```
mamba install -c conda-forge xeus-zmq=1.0.2=h0541b36_2
```

What does it mean however??

**Comment by SylvainCorlay** [comment] 2023-03-21 03:16
@johanmabille could this be the un-pinning of nlohmann_json that we discussed the other day?

**Comment by SylvainCorlay** [comment] 2023-03-21 04:03
@rapgenic I tried the binder you mentioned removing the workaround at https://github.com/SylvainCorlay/XOctaveCH234 and am not seeing the error anymore.

**Comment by JohanMabille** [comment] 2023-03-21 10:40
> @JohanMabille could this be the un-pinning of nlohmann_json that we discussed the other day?

Yes this is exactly the root cause. So basically, previous versions of xeus-zmq had an upper bound on `nlohmann_json`, but this was leading to unsolvable conflicts with other dependencies depending on `nlohmann_json` too. Therefore, we decided to remove this constraint, but this prevented the update for downstream packages unless we rebuild them with latest version of `xeus-zmq`.

**Comment by rapgenic** [comment] 2023-03-24 10:33
I don't really understand what this means for this package in terms of maintenance, more precisely:

* Should we fix something right now (i.e. pin nlohmann_json) or rebuilding the feedstock was enough?
* Could this cause similar problems in the future (i.e. mismatch of library versions -- I think this was what happened --)?
* If so, is there way to detect it automatically?

Thanks!

**Comment by SylvainCorlay** [comment] 2024-07-11 08:56
nlohmann_json now has a full version pinning rule as a run export, so we should be fine. Closing as solved.

**Closed as completed by SylvainCorlay** 2024-07-11 08:56 UTC
